# Build frontend
FROM node:24-alpine AS frontend-build

WORKDIR /web

COPY web/app/package*.json ./

RUN npm ci

COPY web/app/public ./public

COPY web/app/src ./src

COPY web/app/index.html ./

COPY web/app/vite.config.js ./

# Outputs to /web/dist set in vite.config
RUN npm run build     

# Build backend
FROM golang:1.27.1-trixie AS backend-build

WORKDIR /app

COPY . .

RUN go mod download

RUN go install github.com/swaggo/swag/cmd/swag@latest

RUN swag init -g cmd/api/main.go --output docs/ 

ARG VERSION="dev"
ARG BUILD_DATE="unknown"

RUN go build -ldflags "-X main.version=${VERSION} -X main.buildDate=${BUILD_DATE}" -o api ./cmd/api

# Final
FROM debian:trixie-slim

WORKDIR /app

# Copy SPA assets
COPY --from=frontend-build /web/dist /app/web

# Copy Go binary
COPY --from=backend-build /app/api /app/api

RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates

EXPOSE 8000

CMD ["/app/api"]
