// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/session": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] modify a server session.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Update server session admin",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.ServerSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.ServerSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/audit/events": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] retrieve audit events",
                "tags": [
                    "audit"
                ],
                "summary": "Get audit events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/audit.AuditLogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/ldap": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] get the current LDAP config",
                "tags": [
                    "ldap"
                ],
                "summary": "Get LDAP config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ldap.LdapConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] set an LDAP config",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ldap"
                ],
                "summary": "Set LDAP config",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ldap.LdapConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] delete an LDAP config. No payload or selector, as there can be only one configuration.",
                "tags": [
                    "ldap"
                ],
                "summary": "Delete LDAP config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/auth/ldap/users/search": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] search the LDAP service for a user during provisioning. Matches where UPN starts with query and returns one match only.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ldap"
                ],
                "summary": "Search for LDAP user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ldap.LdapSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ldap.LdapSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/oidc": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] get the current OIDC config",
                "tags": [
                    "oidc"
                ],
                "summary": "Get OIDC config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/oidc.OidcConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] set an OIDC config",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "oidc"
                ],
                "summary": "Set OIDC config",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/oidc.OidcConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] delete an OIDC config. No payload or selector, as there can be only one configuration.",
                "tags": [
                    "oidc"
                ],
                "summary": "Delete OIDC config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/auth/oidc/test": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] test the OIDC connection",
                "tags": [
                    "oidc"
                ],
                "summary": "Test OIDC connection",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/encryption/passphrase": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] trigger an automated decrypt and re-encrypt of sensitive data fields within the database with a supplied phrase. Requires updating env var after.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "encryption"
                ],
                "summary": "Rotate encryption phrase",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/encryption.RotateEncryptionPhraseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notification/types": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get all supported notification types",
                "tags": [
                    "notification"
                ],
                "summary": "Get notification types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/notification.NotificationTypeResponse"
                            }
                        }
                    }
                }
            }
        },
        "/session": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Modify own server session.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Update server session",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.ServerSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.ServerSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create a new server session",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "New server session",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/session.ServerSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/session.ServerSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/setup": {
            "post": {
                "description": "Oneshot endpoint allowing the creation of initial admin user when starting the app for the first time or when all users have been deleted from the database. Endpoint is inaccessible during normal operation.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Creating first time user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] Create new user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create new user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] Will return conflict if there are active server sessions. End the sessions before deleting.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Delete target user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.DeleteUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/auth": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get authorisation for current user",
                "tags": [
                    "user"
                ],
                "summary": "Get user auth",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserAuthResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] update authorisation for all target users. All changes must succeed otherwise change is rolled back and error is raised.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update user auth",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.UpdateUserRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/ldap": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] provision an LDAP user. Assumes an LDAP config is present and the user exists in the IDP.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ldap"
                ],
                "summary": "Create LDAP user",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ldap.CreateLdapUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/notification": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get own notification config",
                "tags": [
                    "notification"
                ],
                "summary": "Get notification config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/notification.NotificationConfigResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Set own notification config",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "notification"
                ],
                "summary": "Set notification config",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/notification.NotificationConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Delete own notification config",
                "tags": [
                    "notification"
                ],
                "summary": "Delete notification config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/user/notification/test": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Test own notification config and receive a message",
                "tags": [
                    "notification"
                ],
                "summary": "Test notification config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/user/password": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Change own password",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Change own password",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "[Admin] retrieve all users in the system including attributes",
                "tags": [
                    "user"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.GetUsersResponse"
                            }
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get current version of ez2boot",
                "tags": [
                    "util"
                ],
                "summary": "Get version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/util.VersionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audit.AuditLogEvent": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "actorEmail": {
                    "type": "string"
                },
                "actorUserID": {
                    "type": "integer",
                    "format": "int64"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "reason": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "targetEmail": {
                    "type": "string"
                },
                "targetUserID": {
                    "type": "integer",
                    "format": "int64"
                },
                "timeStamp": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "audit.AuditLogResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/audit.AuditLogEvent"
                    }
                },
                "next_cursor": {
                    "type": "integer"
                }
            }
        },
        "encryption.RotateEncryptionPhraseRequest": {
            "type": "object",
            "properties": {
                "phrase": {
                    "type": "string"
                }
            }
        },
        "ldap.CreateLdapUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "ldap.LdapConfigRequest": {
            "type": "object",
            "properties": {
                "base_dn": {
                    "type": "string"
                },
                "bind_dn": {
                    "type": "string"
                },
                "bind_password": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "skip_tls_verify": {
                    "type": "boolean"
                },
                "use_ssl": {
                    "type": "boolean"
                }
            }
        },
        "ldap.LdapConfigResponse": {
            "type": "object",
            "properties": {
                "base_dn": {
                    "type": "string"
                },
                "bind_dn": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "skip_tls_verify": {
                    "type": "boolean"
                },
                "use_ssl": {
                    "type": "boolean"
                }
            }
        },
        "ldap.LdapSearchRequest": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                }
            }
        },
        "ldap.LdapSearchResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "notification.NotificationConfigRequest": {
            "type": "object",
            "properties": {
                "channel_config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "notification.NotificationConfigResponse": {
            "type": "object",
            "properties": {
                "channel_config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "notification.NotificationTypeResponse": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "oidc.OidcConfigRequest": {
            "type": "object",
            "properties": {
                "app_url": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "issuer_url": {
                    "type": "string"
                }
            }
        },
        "oidc.OidcConfigResponse": {
            "type": "object",
            "properties": {
                "app_url": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "issuer_url": {
                    "type": "string"
                }
            }
        },
        "session.ServerSessionRequest": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "server_group": {
                    "type": "string"
                }
            }
        },
        "session.ServerSessionResponse": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "expiry": {
                    "type": "string"
                },
                "server_group": {
                    "type": "string"
                }
            }
        },
        "user.ChangePasswordRequest": {
            "type": "object",
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                }
            }
        },
        "user.CreateUserRequest": {
            "type": "object",
            "properties": {
                "api_enabled": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "ui_enabled": {
                    "type": "boolean"
                }
            }
        },
        "user.DeleteUserRequest": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "user.GetUsersResponse": {
            "type": "object",
            "properties": {
                "api_enabled": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "identity_provider": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "last_login": {
                    "type": "integer"
                },
                "ui_enabled": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "user.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "api_enabled": {
                    "type": "boolean"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "ui_enabled": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "user.UserAuthResponse": {
            "type": "object",
            "properties": {
                "api_enabled": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "identity_provider": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "mfa_confirmed": {
                    "type": "boolean"
                },
                "ui_enabled": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "util.VersionResponse": {
            "type": "object",
            "properties": {
                "build_date": {
                    "type": "string"
                },
                "checked_at": {
                    "type": "integer"
                },
                "latest_release": {
                    "type": "string"
                },
                "release_url": {
                    "type": "string"
                },
                "update_available": {
                    "type": "boolean"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ez2boot API",
	Description:      "All endpoints return responses wrapped in a standard envelope: {\"success\": bool, \"data\": (schema shown per endpoint), \"error\": string}. All protected endpoints can return 401.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
